#!/usr/bin/env python3
"""Project Euler Problem 045

Triangle, pentagonal, and hexagonal numbers are generated by 
the following formulae:
Triangle        T_(n)=n(n+1)/2      1, 3, 6, 10, 15, ...
Pentagonal      P_(n)=n(3n−1)/2     1, 5, 12, 22, 35, ...
Hexagonal       H_(n)=n(2n−1)       1, 6, 15, 28, 45, ...

It can be verified that T_(285) = P_(165) = H_(143) = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

triNums  = set()
penNums  = set()
hexNums  = set()

for n in range(1000000):
    triNums.add(int(n*(n+1)/2))
    penNums.add(int(n*(3*n-1)/2))
    hexNums.add(int(n*(2*n-1)))

tphNums = triNums & penNums & hexNums
print(tphNums)
